In [11]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd

df = pd.read_json("../data/totto/linearized/train.jsonl", lines=True)

In [6]:
df.columns

Index(['table', 'table_webpage_url', 'table_page_title', 'table_section_title',
       'table_section_text', 'highlighted_cells', 'example_id',
       'sentence_annotations', 'full_table_str', 'subtable_str',
       'full_table_metadata_str', 'subtable_metadata_str'],
      dtype='object')

In [8]:
import json

tables = df["table"].apply(lambda x: pd.DataFrame(json.loads(x)))

In [9]:
titles = df["table_page_title"].values.tolist()

In [66]:
sentences = df["sentence_annotations"].apply(lambda x: x[0])

In [12]:
from kilt.knowledge_source import KnowledgeSource

ks = KnowledgeSource()

In [78]:
import regex as re

def number_matching(sentence, table):
    values = table.values.flatten().tolist()
    numbers = [x[0] for x in re.findall("(\d+(.\d+)?)", " ".join(values))]
    count = 0
    for number1 in re.findall("(\d+(.\d+)?)", sentence):
        for number2 in numbers:
            if number1[0] == number2:
                count += 1
                break
    return count >= 3
            
    
def row_matching(sentence, table):
    for idx, row in table.iterrows():
        count = 0

        for val1 in row.values:
            if val1 in sentence:
                count += 1
                break
        return count >= 3

In [82]:
from blingfire import *
examples = []

for title, table in list(zip(titles, tables))[:30]:
        page = ks.get_page_by_title(title)
        if page is None:
            examples.append(([], table))
            continue
            
        page = page["text"]
        t_sentences = []
        for passage in page:
            for sentence in text_to_sentences(passage).split("\n"):
                if number_matching(sentence, table) or row_matching(sentence, table):
                    t_sentences.append(sentence)
        
        examples.append((t_sentences, table))

In [83]:
for example, sentence, title in zip(examples, sentences, titles):
    print(example, sentence, title)
    print("\n")
    print("\n")
    print("\n")

([],      #                                   Run                 Title Chapters  \
0   59        June 5, 2000— February 2, 2001      Laços de Família      209
1   60  February 5, 2001— September 28, 2001    Porto dos Milagres      203
2   61        October 1, 2001— June 14, 2002               O Clone      221
3   62      June 17, 2002— February 14, 2003             Esperança      209
4   63   February 17, 2003— October 10, 2003  Mulheres Apaixonadas      203
5   64       October 13, 2003— June 25, 2004           Celebridade      221
6   65         June 28, 2004— March 11, 2005    Senhora do Destino      221
7   66      March 14, 2005— November 4, 2005               América      203
8   67        November 7, 2005— July 7, 2006             Belíssima      209
9   68          July 10, 2006— March 2, 2007       Páginas da Vida      203
10  69     March 5, 2007— September 28, 2007      Paraíso Tropical      179
11  70         October 1, 2007— May 31, 2008            Duas Caras      210
12  71        June 2, 2008— January 16, 2009            A Favorita      197
13  72  January 19, 2009— September 11, 2009    Caminho das Índias      203
14  73      September 14, 2009— May 14, 2010          Viver a Vida      209

                              Author                           Director  \
0                      Manoel Carlos                 Ricardo Waddington
1   Aguinaldo Silva Ricardo Linhares                Marcos Paulo Simões
2                       Glória Perez                    Jayme Monjardim
3               Benedito Ruy Barbosa                      Luiz Fernando
4                      Manoel Carlos                 Ricardo Waddington
5                     Gilberto Braga                    Dennis Carvalho
6                    Aguinaldo Silva                          Wolf Maya
7                       Glória Perez  Jayme Monjardim Marcos Schechtman
8                    Sílvio de Abreu                    Denise Saraceni
9                      Manoel Carlos                    Jayme Monjardim
10   Gilberto Braga Ricardo Linhares                    Dennis Carvalho
11                   Aguinaldo Silva                          Wolf Maya
12             João Emanuel Carneiro                 Ricardo Waddington
13                      Glória Perez                  Marcos Schechtman
14                     Manoel Carlos                    Jayme Monjardim

   Ibope Rating
0          44.9
1          44.6
2          47.0
3          37.7
4          46.6
5          46.0
6          50.4
7          49.4
8          48.5
9          46.8
10         42.8
11         41.1
12         39.5
13         38.8
14         35.6  ) {'original_sentence': 'It is also the first telenovela by the writer to air in the 9 pm timeslot.', 'sentence_after_deletion': 'It is the telenovela air in the 9 pm timeslot.', 'sentence_after_ambiguity': 'A Favorita is the telenovela aired in the 9 pm timeslot.', 'final_sentence': 'A Favorita is the telenovela aired in the 9 pm timeslot.'} List of 8/9 PM telenovelas of Rede Globo






(['Early cars used 3.6-litre V8s, while later cars featured a 4.2-litre version of the engine.', 'The Audi V8 was replaced by the Audi A8 in 1994, although the A8 was not sold in North America until 1996.', "Standard features for the Audi V8 included a 32-valve, double overhead camshaft (DOHC) V8 engine and a four-speed electronically controlled ZF 4HP24A automatic transmission providing Audi's quattro permanent four-wheel drive system.", 'This tradition would continue with the A8, offered in "A8L" format (though only in year 2010 A8L reached the size of the V8L).', 'Powertrain detail of the Audi V8 featured one of two all-new, all-aluminium alloy engines – both petrol engines, and both in V8 configuration with 32 valves (four valves per cylinder) with dual valve springs, and four overhead camshafts (DOHC).', 'The intervals for changing the timing belts varied; the 3.6\xa0V8 (PT) required changing every , whereas the 4.2\xa0V8 (ABH) had a longer interval at .', "Whilst the 3.6\xa0V8 was able to use 95\xa0RON (91\xa0AKI) fuel, for the 4.2\xa0V8, the more expensive 98\xa0RON (93\xa0AKI) 'SuperPlus' unleaded was required in order to achieve the quoted power output.", 'The usage of 95\xa0RON in the 4.2\xa0V8 resulted in a lower power output, as well as increased fuel consumption.', 'This V8 engine was DIN-rated with a maximum motive power output of at 5,800\xa0revolutions per minute (rpm), and generated a torque turning force of at 4,000\xa0rpm.', 'In August 1991, Audi introduced a 4.2-litre engine, displacing , to complement the choice of the existing 3.6-litre V8.', 'This shared many components from the 3.6\xa0V8, and the 4.2 unit was identical to the optional V8 used in the Audi S4 (aka "Ur-S4"), sharing the same rated outputs and ABH identification code.', 'A ZF Friedrichshafen-sourced four-speed 4HP24A automatic transmission with a torque converter was available throughout the V8 production run.', 'Audi developed a Group A competition version of the Audi V8 for entry into the Deutsche Tourenwagen Meisterschaft (DTM) (German Touring Car Championship) auto racing series equipped with , later , 3.6 V8 engine and 6-speed manual transmission, and began racing with it in 1990 with Schmidt MotorSport (SMS) running the operation, and Hans-Joachim Stuck, Walter Röhrl and Frank Jelinski driving.'],   Engine (code)     Displacement, Type Valvetrain  \
0   3.6 V8 (PT)  3,562 cc V8 engine 32 valve DOHC
1  4.2 V8 (ABH)  4,172 cc V8 engine 32 valve DOHC

                        Fuel grade Max. Motive Power at rpm (DIN 80/1269/EWG)  \
0  95 RON (91 AKI) unleaded petrol           184 kW (250 PS; 247 bhp) @ 5,800
1  98 RON (93 AKI) unleaded petrol           206 kW (280 PS; 276 bhp) @ 5,800

             Max. torque at rpm                    Transmissions  \
0  340 N⋅m (251 lbf⋅ft) @ 4,000  4-sp ZF 4HP24A auto 5-sp manual
1  400 N⋅m (295 lbf⋅ft) @ 4,000  4-sp ZF 4HP24A auto 6-sp manual

  0-100 km/h (62.1 mph)                                    Top speed  \
0   9.9 secs‡ 7.6 secs*  232 km/h (144.2 mph)‡ 244 km/h (151.6 mph)*
1   7.7 secs‡ 6.8 secs*                         250 km/h (155.3 mph)

           Dates  \
0  10/88 ÷ 11/93
1  08/91 ÷ 11/93

  Dates of Top speed of 0-100 km/h (62.1 mph) of Transmissions of Max. torque at rpm of Max. Motive Power at rpm (DIN 80/1269/EWG) of Fuel grade of Displacement, Type Valvetrain of Engine (code)
0
1                                                                                                                                                                                                   ) {'original_sentence': 'In August 1991, Audi introduced a 4.2-litre engine, displacing 4,172 cubic centimetres (254.6 cu in), to complement the choice of the existing 3.6-litre V8.', 'sentence_after_deletion': 'Audi introduced a 4.2-litre engine, displacing 4,172 cubic centimetres.', 'sentence_after_ambiguity': 'Audi introduced a 4.2-litre engine with displacing 4,172 cubic centimetres.', 'final_sentence': 'Audi introduced a 4.2-litre engine with displacing 4,172 cubic centimetres.'} Audi V8






(['Elagabalus (), also known as Heliogabalus (; 204 – 11 March 222), was Roman emperor from 218 to 222.'],                                                    0  \
0  Elagabalus Severan dynastyBorn: c.204 Died: 11...
1
2
3

                    Regnal titles  \
0
1  Succeeded by Severus Alexander
2
3

                  Political offices of Regnal titles
0
1
2  Succeeded by Gaius Vettius Gratus Sabinianus, ...
3  Succeeded by Marius Maximus, Luscius Roscius A...  ) {'original_sentence': 'Elagabalus (/ˌɛləˈɡæbələs/), also known as Heliogabalus (Latin: Marcus Aurelius Antoninus Augustus; c. 204 – 11 March 222), was Roman emperor from 218 to 222.', 'sentence_after_deletion': 'Elagabalus (204 – 11 March 222), was Roman emperor from 218 to 222.', 'sentence_after_ambiguity': 'Elagabalus (204 – 11 March 222), was Roman emperor from 218 to 222.', 'final_sentence': 'Elagabalus (204 – 11 March 222) was Roman emperor from 218 to 222.'} Elagabalus






(["It met in Washington, DC from January 3, 1943, to January 3, 1945, during the last two years of Franklin D. Roosevelt's presidency.", 'BULLET::::- December 17, 1943: Magnuson Act (Chinese Exclusion Repeal Act of 1943), Sess. 1, ch. 344, ', 'BULLET::::- February 3, 1944: Mustering-out Payment Act, Sess. 2, , ', "BULLET::::- June 6, 1944: Servicemen's Readjustment Act of 1944 (G.I. Bill), Sess. 2, ch. 268, , ", 'BULLET::::- July 1, 1944: Public Health Service Act, Sess. 2, ch. 373, ', 'BULLET::::- December 22, 1944: Pick-Sloan Flood Control Act, Sess. 2, ch. 665, , ', 'Preceding the names in the list below are Senate class numbers, which indicate the cycle of their election, In this Congress, Class 3 meant their term ended with this Congress, facing re-election in 1944; Class 1 meant their term began in the last Congress, facing re-election in 1946; and Class 2 meant their term began in this Congress, facing re-election in 1948.', 'BULLET::::- Samuel D. Jackson (D), January 28, 1944 – November 13, 1944 ', 'BULLET::::- Sinclair Weeks (R), February 8, 1944 – December 19, 1944 ', 'BULLET::::- Arthur Walsh (D), November 26, 1943 – December 7, 1944 '],         State (class)                     Vacator  \
0      New Jersey (1)  William Warren Barbour (R)
1         Indiana (3)      Frederick Van Nuys (D)
2   Massachusetts (2)  Henry Cabot Lodge, Jr. (R)
3          Oregon (2)       Charles L. McNary (R)
4      Washington (3)              Homer Bone (D)
5         Indiana (3)       Samuel D. Jackson (D)
6  South Carolina (3)    Ellison Durant Smith (D)
7      New Jersey (1)            Arthur Walsh (D)
8   Massachusetts (2)          Sinclair Weeks (R)

                                   Reason for change  \
0  Died November 22, 1943. Successor was appointe...
1  Died January 25, 1944. Successor was appointed...
2  Resigned February 3, 1944, to go on active dut...
3  Died February 25, 1944. Successor was appointe...
4  Resigned November 13, 1944, to become Judge of...
5  Appointee was not a candidate to finish the te...
6                            Died November 17, 1944.
7  Appointee was not a candidate to finish the te...
8  Appointee was not a candidate to finish the te...

                  Successor Date of successor's formal installation
0          Arthur Walsh (D)                       November 26, 1943
1     Samuel D. Jackson (D)                        January 28, 1944
2        Sinclair Weeks (R)                        February 8, 1944
3            Guy Cordon (R)                           March 4, 1944
4       Warren Magnuson (D)                       December 14, 1944
5     William E. Jenner (R)                        November 7, 1944
6        Wilton E. Hall (D)                       November 20, 1944
7    H. Alexander Smith (R)                        December 7, 1944
8  Leverett Saltonstall (R)                         January 4, 1945  ) {'original_sentence': 'William Warren Barbour (R), until November 22, 1943 Arthur Walsh (D), November 26, 1943 – December 7, 1944 H. Alexander Smith (R), from December 7, 1944 2.', 'sentence_after_deletion': 'William Warren Barbour (R), until November 22, 1943 Arthur Walsh (D), November 26, 1943 H. Alexander Smith (R), from December 7, 1944.', 'sentence_after_ambiguity': 'William Warren Barbour (R) served as Senate until November 22, 1943, then by Arthur Walsh (D) from November 26, 1943 and was succeeded by H. Alexander Smith (R), from December 7, 1944.', 'final_sentence': 'William Warren Barbour (R) served as Senate until November 22, 1943, then by Arthur Walsh (D) from November 26, 1943 and was succeeded by H. Alexander Smith (R), from December 7, 1944.'} 78th United States Congress






([],                 Chart (2013) Peak Position
0  Hungarian Albums (MAHASZ)            14
1           US Billboard 200           119) {'original_sentence': 'Commercial performance Countdown to Extinction: Live sold about 3600 copies in the U.S. during its first week, enough to reach number 119 on the Billboard 200.', 'sentence_after_deletion': 'Countdown to Extinction: Live reach 119 on the Billboard 200.', 'sentence_after_ambiguity': 'The Countdown to Extinction: Live reached 119 on the Billboard 200.', 'final_sentence': 'The Countdown to Extinction: Live reached 119 on the Billboard 200.'} Countdown to Extinction: Live






([],   HIV infected & AIDS deaths
0                AIDS deaths
1                        107
2                        087
3                        655
4                      1,848
5                      2,792
6                      2,859) {'original_sentence': 'There were 439 Malaria incidence for every 1,000 people in the province as of 2005 and there were 2,859 AIDS death as of 2010.', 'sentence_after_deletion': 'There were 2,859 AIDS death as of 2010.', 'sentence_after_ambiguity': 'There were 2,859 AIDS death as of 2010 in North-Western Province.', 'final_sentence': 'There were 2,859 AIDS death as of 2010 in North-Western Province.'} North-Western Province, Zambia






([],                                                 Year                 Award  \
0                                               1958            Tony Award
1   Best Performance by a Leading Actor in a Musical          Larry Blyden
2  Best Performance by a Leading Actress in a Mus...         Miyoshi Umeki
3                                  Best Choreography           Carol Haney
4                Best Conductor and Musical Director  Salvatore Dell'Isola
5                                Best Costume Design          Irene Sharif

  Nominee of Category     Result Ref   Category
0        Best Musical  Nominated
1                                     Nominated
2                                     Nominated
3                                     Nominated
4                                           Won
5                                     Nominated  ) {'original_sentence': "The show received six Tony Award nominations, but won only one Tony (Best Conductor and Musical Director, for Salvatore Dell'Isola).", 'sentence_after_deletion': "The show received six Tony Award nominations, but won only one (Best Conductor and Musical Director, for Salvatore Dell'Isola).", 'sentence_after_ambiguity': "The Flower Drum Song received six Tony Award nominations, but won only one for the Best Conductor and Musical Director, for Salvatore Dell'Isola.", 'final_sentence': "The Flower Drum Song received six Tony Award nominations, but won only one for the Best Conductor and Musical Director, for Salvatore Dell'Isola."} Flower Drum Song






([],       Party                 Candidate   Votes      %      ±  \
0   Liberal        Harcourt Johnstone  14,824   60.6  +13.4
1  Unionist  George Frederick Stanley   9,648   39.4   13.4
2                                       5,176   21.2   26.8
3                                               60.2   +1.8
4                                              +13.4

  Turnout of Majority of Party Turnout of Majority of Candidate of Party
0
1
2
3
4                                             Liberal gain from Unionist  ) {'original_sentence': 'The result was a gain for the Liberal Party from the Unionists with Johnstone gaining 60% of the poll and a majority of 5,176 over Stanley.', 'sentence_after_deletion': 'The result was a gain for the Liberal Party from the Unionists with Johnstone gaining a majority of 5,176 over Stanley.', 'sentence_after_ambiguity': 'The result was a gain for the Liberal Party from the Unionists with Johnstone gaining a majority of 5,176 over Stanley.', 'final_sentence': 'In 1923 Willesden East by-elections, the result was a gain for the Liberal Party from the Unionists, with Johnstone gaining a majority of 5,176 over Stanley.'} 1923 Willesden East by-election






([],      Date   Time              Score  Set 1  Set 2  Set 3  Set 4 Set 5  Total  \
0  20 Jul  19:30  Netherlands   3–1  25–21  25–18  20–25  25–23        95–87

   Report
0  Report  ) {'original_sentence': 'The tournament was won by Slovakia, defeating the Netherlands by 3–1 in the finals.', 'sentence_after_deletion': 'The tournament was won by Slovakia, defeating the Netherlands by 3–1 in the finals.', 'sentence_after_ambiguity': "The 2008 Men's European Volleyball League was won by Slovakia, defeating the Netherlands by 3–1 in the finals.", 'final_sentence': "The 2008 Men's European Volleyball League was won by Slovakia, defeating the Netherlands by 3–1 in the finals."} 2008 Men's European Volleyball League






([],                   Species Species Common Name NCBI Accession Number (Protein)  \
0            Homo Sapiens               Human                       NP_444509
1         Pan Troglodytes          Chimpanzee                    XP_001139122
2     Macaca Fascicularis             Macaque                  XP_005562638.1
3   Neterocephalus Glaber      Naked mole rat                    XP_004848509
4             Felis Catus                 Cat                    XP_003984890
5          Equus Caballus               Horse                    XP_001497968
6      Alligator Sinensis   Chinese Alligator                    XP_006028215
7     Anolis Carolinensis      Carolina Anole                    XP_003227984
8             Danio Rerio           Zebrafish                      NP_1020721
9     Latimeria Chalumnae  African Coelacanth                     XP_05994570
10     Ciona Intestinalis          Sea Squirt                    XP_002123421

   Amino Acid Length Protein Identity  \
0                214             100%
1                214              99%
2                214              96%
3                214              84%
4                209              80%
5                203              80%
6                211              70%
7                215              64%
8                204              59%
9                148              43%
10               255              27%

   Divergence date from Humans (million years ago)
0                                                0
1                                              6.3
2                                               29
3                                             92.3
4                                             94.2
5                                             94.2
6                                              296
7                                              296
8                                            400.1
9                                            414.9
10                                           722.5  ) {'original_sentence': 'The gene that encodes FAM167A is 214 amino acids in length.', 'sentence_after_deletion': 'The FAM167A is 214 amino acids in length.', 'sentence_after_ambiguity': 'The FAM167A has 214 amino acids in length.', 'final_sentence': 'The FAM167A has an amino acid length of 214.'} FAM167A






([],   Representing Ethiopia of Year Representing Ethiopia of Competition  \
0                          2012                        Olympic Games
1                          2013                  World Championships
2                          2015                  World Championships
3                          2016                African Championships
4                 Olympic Games               Rio de Janeiro, Brazil
5                          2017                  World Championships

  Representing Ethiopia of Venue Representing Ethiopia of Position  \
0         London, United Kingdom                               6th
1                 Moscow, Russia                               5th
2                 Beijing, China                          17th (h)
3           Durban, South Africa                                 –
4                           15th                    3000 m s'chase
5         London, United Kingdom                               7th

  Representing Ethiopia of Event Representing Ethiopia of Notes
0                     3000 m st.                        9:19.89